// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GmPacketReader.proto

public final class GmPacketReaderOuterClass {
  private GmPacketReaderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GmHeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GmHeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currentTime = 1;</code>
     * @return The currentTime.
     */
    java.lang.String getCurrentTime();
    /**
     * <code>string currentTime = 1;</code>
     * @return The bytes for currentTime.
     */
    com.google.protobuf.ByteString
        getCurrentTimeBytes();
  }
  /**
   * Protobuf type {@code GmHeartBeat}
   */
  public static final class GmHeartBeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GmHeartBeat)
      GmHeartBeatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GmHeartBeat.newBuilder() to construct.
    private GmHeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GmHeartBeat() {
      currentTime_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GmHeartBeat();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GmHeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currentTime_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GmPacketReaderOuterClass.internal_static_GmHeartBeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GmPacketReaderOuterClass.internal_static_GmHeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GmPacketReaderOuterClass.GmHeartBeat.class, GmPacketReaderOuterClass.GmHeartBeat.Builder.class);
    }

    public static final int CURRENTTIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object currentTime_;
    /**
     * <code>string currentTime = 1;</code>
     * @return The currentTime.
     */
    @java.lang.Override
    public java.lang.String getCurrentTime() {
      java.lang.Object ref = currentTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentTime_ = s;
        return s;
      }
    }
    /**
     * <code>string currentTime = 1;</code>
     * @return The bytes for currentTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrentTimeBytes() {
      java.lang.Object ref = currentTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentTime_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currentTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentTime_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currentTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GmPacketReaderOuterClass.GmHeartBeat)) {
        return super.equals(obj);
      }
      GmPacketReaderOuterClass.GmHeartBeat other = (GmPacketReaderOuterClass.GmHeartBeat) obj;

      if (!getCurrentTime()
          .equals(other.getCurrentTime())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GmPacketReaderOuterClass.GmHeartBeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GmPacketReaderOuterClass.GmHeartBeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GmPacketReaderOuterClass.GmHeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GmPacketReaderOuterClass.GmHeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GmPacketReaderOuterClass.GmHeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GmPacketReaderOuterClass.GmHeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GmPacketReaderOuterClass.GmHeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GmPacketReaderOuterClass.GmHeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GmPacketReaderOuterClass.GmHeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GmPacketReaderOuterClass.GmHeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GmPacketReaderOuterClass.GmHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GmPacketReaderOuterClass.GmHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GmPacketReaderOuterClass.GmHeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GmHeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GmHeartBeat)
        GmPacketReaderOuterClass.GmHeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GmPacketReaderOuterClass.internal_static_GmHeartBeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GmPacketReaderOuterClass.internal_static_GmHeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GmPacketReaderOuterClass.GmHeartBeat.class, GmPacketReaderOuterClass.GmHeartBeat.Builder.class);
      }

      // Construct using GmPacketReaderOuterClass.GmHeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currentTime_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GmPacketReaderOuterClass.internal_static_GmHeartBeat_descriptor;
      }

      @java.lang.Override
      public GmPacketReaderOuterClass.GmHeartBeat getDefaultInstanceForType() {
        return GmPacketReaderOuterClass.GmHeartBeat.getDefaultInstance();
      }

      @java.lang.Override
      public GmPacketReaderOuterClass.GmHeartBeat build() {
        GmPacketReaderOuterClass.GmHeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GmPacketReaderOuterClass.GmHeartBeat buildPartial() {
        GmPacketReaderOuterClass.GmHeartBeat result = new GmPacketReaderOuterClass.GmHeartBeat(this);
        result.currentTime_ = currentTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GmPacketReaderOuterClass.GmHeartBeat) {
          return mergeFrom((GmPacketReaderOuterClass.GmHeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GmPacketReaderOuterClass.GmHeartBeat other) {
        if (other == GmPacketReaderOuterClass.GmHeartBeat.getDefaultInstance()) return this;
        if (!other.getCurrentTime().isEmpty()) {
          currentTime_ = other.currentTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GmPacketReaderOuterClass.GmHeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GmPacketReaderOuterClass.GmHeartBeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object currentTime_ = "";
      /**
       * <code>string currentTime = 1;</code>
       * @return The currentTime.
       */
      public java.lang.String getCurrentTime() {
        java.lang.Object ref = currentTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentTime = 1;</code>
       * @return The bytes for currentTime.
       */
      public com.google.protobuf.ByteString
          getCurrentTimeBytes() {
        java.lang.Object ref = currentTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentTime = 1;</code>
       * @param value The currentTime to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currentTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currentTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentTime() {
        
        currentTime_ = getDefaultInstance().getCurrentTime();
        onChanged();
        return this;
      }
      /**
       * <code>string currentTime = 1;</code>
       * @param value The bytes for currentTime to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currentTime_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GmHeartBeat)
    }

    // @@protoc_insertion_point(class_scope:GmHeartBeat)
    private static final GmPacketReaderOuterClass.GmHeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GmPacketReaderOuterClass.GmHeartBeat();
    }

    public static GmPacketReaderOuterClass.GmHeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GmHeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<GmHeartBeat>() {
      @java.lang.Override
      public GmHeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GmHeartBeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GmHeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GmHeartBeat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GmPacketReaderOuterClass.GmHeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GmPacketReaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GmPacketReader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
     */
    java.util.List<GmPacketReaderOuterClass.GmHeartBeat> 
        getGmHeartBeatList();
    /**
     * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
     */
    GmPacketReaderOuterClass.GmHeartBeat getGmHeartBeat(int index);
    /**
     * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
     */
    int getGmHeartBeatCount();
    /**
     * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
     */
    java.util.List<? extends GmPacketReaderOuterClass.GmHeartBeatOrBuilder> 
        getGmHeartBeatOrBuilderList();
    /**
     * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
     */
    GmPacketReaderOuterClass.GmHeartBeatOrBuilder getGmHeartBeatOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GmPacketReader}
   */
  public static final class GmPacketReader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GmPacketReader)
      GmPacketReaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GmPacketReader.newBuilder() to construct.
    private GmPacketReader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GmPacketReader() {
      gmHeartBeat_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GmPacketReader();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GmPacketReader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                gmHeartBeat_ = new java.util.ArrayList<GmPacketReaderOuterClass.GmHeartBeat>();
                mutable_bitField0_ |= 0x00000001;
              }
              gmHeartBeat_.add(
                  input.readMessage(GmPacketReaderOuterClass.GmHeartBeat.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          gmHeartBeat_ = java.util.Collections.unmodifiableList(gmHeartBeat_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GmPacketReaderOuterClass.internal_static_GmPacketReader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GmPacketReaderOuterClass.internal_static_GmPacketReader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GmPacketReaderOuterClass.GmPacketReader.class, GmPacketReaderOuterClass.GmPacketReader.Builder.class);
    }

    public static final int GMHEARTBEAT_FIELD_NUMBER = 1;
    private java.util.List<GmPacketReaderOuterClass.GmHeartBeat> gmHeartBeat_;
    /**
     * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
     */
    @java.lang.Override
    public java.util.List<GmPacketReaderOuterClass.GmHeartBeat> getGmHeartBeatList() {
      return gmHeartBeat_;
    }
    /**
     * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends GmPacketReaderOuterClass.GmHeartBeatOrBuilder> 
        getGmHeartBeatOrBuilderList() {
      return gmHeartBeat_;
    }
    /**
     * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
     */
    @java.lang.Override
    public int getGmHeartBeatCount() {
      return gmHeartBeat_.size();
    }
    /**
     * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
     */
    @java.lang.Override
    public GmPacketReaderOuterClass.GmHeartBeat getGmHeartBeat(int index) {
      return gmHeartBeat_.get(index);
    }
    /**
     * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
     */
    @java.lang.Override
    public GmPacketReaderOuterClass.GmHeartBeatOrBuilder getGmHeartBeatOrBuilder(
        int index) {
      return gmHeartBeat_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < gmHeartBeat_.size(); i++) {
        output.writeMessage(1, gmHeartBeat_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < gmHeartBeat_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, gmHeartBeat_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GmPacketReaderOuterClass.GmPacketReader)) {
        return super.equals(obj);
      }
      GmPacketReaderOuterClass.GmPacketReader other = (GmPacketReaderOuterClass.GmPacketReader) obj;

      if (!getGmHeartBeatList()
          .equals(other.getGmHeartBeatList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGmHeartBeatCount() > 0) {
        hash = (37 * hash) + GMHEARTBEAT_FIELD_NUMBER;
        hash = (53 * hash) + getGmHeartBeatList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GmPacketReaderOuterClass.GmPacketReader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GmPacketReaderOuterClass.GmPacketReader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GmPacketReaderOuterClass.GmPacketReader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GmPacketReaderOuterClass.GmPacketReader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GmPacketReaderOuterClass.GmPacketReader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GmPacketReaderOuterClass.GmPacketReader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GmPacketReaderOuterClass.GmPacketReader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GmPacketReaderOuterClass.GmPacketReader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GmPacketReaderOuterClass.GmPacketReader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GmPacketReaderOuterClass.GmPacketReader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GmPacketReaderOuterClass.GmPacketReader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GmPacketReaderOuterClass.GmPacketReader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GmPacketReaderOuterClass.GmPacketReader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GmPacketReader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GmPacketReader)
        GmPacketReaderOuterClass.GmPacketReaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GmPacketReaderOuterClass.internal_static_GmPacketReader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GmPacketReaderOuterClass.internal_static_GmPacketReader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GmPacketReaderOuterClass.GmPacketReader.class, GmPacketReaderOuterClass.GmPacketReader.Builder.class);
      }

      // Construct using GmPacketReaderOuterClass.GmPacketReader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGmHeartBeatFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (gmHeartBeatBuilder_ == null) {
          gmHeartBeat_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          gmHeartBeatBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GmPacketReaderOuterClass.internal_static_GmPacketReader_descriptor;
      }

      @java.lang.Override
      public GmPacketReaderOuterClass.GmPacketReader getDefaultInstanceForType() {
        return GmPacketReaderOuterClass.GmPacketReader.getDefaultInstance();
      }

      @java.lang.Override
      public GmPacketReaderOuterClass.GmPacketReader build() {
        GmPacketReaderOuterClass.GmPacketReader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GmPacketReaderOuterClass.GmPacketReader buildPartial() {
        GmPacketReaderOuterClass.GmPacketReader result = new GmPacketReaderOuterClass.GmPacketReader(this);
        int from_bitField0_ = bitField0_;
        if (gmHeartBeatBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            gmHeartBeat_ = java.util.Collections.unmodifiableList(gmHeartBeat_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.gmHeartBeat_ = gmHeartBeat_;
        } else {
          result.gmHeartBeat_ = gmHeartBeatBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GmPacketReaderOuterClass.GmPacketReader) {
          return mergeFrom((GmPacketReaderOuterClass.GmPacketReader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GmPacketReaderOuterClass.GmPacketReader other) {
        if (other == GmPacketReaderOuterClass.GmPacketReader.getDefaultInstance()) return this;
        if (gmHeartBeatBuilder_ == null) {
          if (!other.gmHeartBeat_.isEmpty()) {
            if (gmHeartBeat_.isEmpty()) {
              gmHeartBeat_ = other.gmHeartBeat_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGmHeartBeatIsMutable();
              gmHeartBeat_.addAll(other.gmHeartBeat_);
            }
            onChanged();
          }
        } else {
          if (!other.gmHeartBeat_.isEmpty()) {
            if (gmHeartBeatBuilder_.isEmpty()) {
              gmHeartBeatBuilder_.dispose();
              gmHeartBeatBuilder_ = null;
              gmHeartBeat_ = other.gmHeartBeat_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gmHeartBeatBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGmHeartBeatFieldBuilder() : null;
            } else {
              gmHeartBeatBuilder_.addAllMessages(other.gmHeartBeat_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GmPacketReaderOuterClass.GmPacketReader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GmPacketReaderOuterClass.GmPacketReader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<GmPacketReaderOuterClass.GmHeartBeat> gmHeartBeat_ =
        java.util.Collections.emptyList();
      private void ensureGmHeartBeatIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          gmHeartBeat_ = new java.util.ArrayList<GmPacketReaderOuterClass.GmHeartBeat>(gmHeartBeat_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GmPacketReaderOuterClass.GmHeartBeat, GmPacketReaderOuterClass.GmHeartBeat.Builder, GmPacketReaderOuterClass.GmHeartBeatOrBuilder> gmHeartBeatBuilder_;

      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public java.util.List<GmPacketReaderOuterClass.GmHeartBeat> getGmHeartBeatList() {
        if (gmHeartBeatBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gmHeartBeat_);
        } else {
          return gmHeartBeatBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public int getGmHeartBeatCount() {
        if (gmHeartBeatBuilder_ == null) {
          return gmHeartBeat_.size();
        } else {
          return gmHeartBeatBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public GmPacketReaderOuterClass.GmHeartBeat getGmHeartBeat(int index) {
        if (gmHeartBeatBuilder_ == null) {
          return gmHeartBeat_.get(index);
        } else {
          return gmHeartBeatBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public Builder setGmHeartBeat(
          int index, GmPacketReaderOuterClass.GmHeartBeat value) {
        if (gmHeartBeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGmHeartBeatIsMutable();
          gmHeartBeat_.set(index, value);
          onChanged();
        } else {
          gmHeartBeatBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public Builder setGmHeartBeat(
          int index, GmPacketReaderOuterClass.GmHeartBeat.Builder builderForValue) {
        if (gmHeartBeatBuilder_ == null) {
          ensureGmHeartBeatIsMutable();
          gmHeartBeat_.set(index, builderForValue.build());
          onChanged();
        } else {
          gmHeartBeatBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public Builder addGmHeartBeat(GmPacketReaderOuterClass.GmHeartBeat value) {
        if (gmHeartBeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGmHeartBeatIsMutable();
          gmHeartBeat_.add(value);
          onChanged();
        } else {
          gmHeartBeatBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public Builder addGmHeartBeat(
          int index, GmPacketReaderOuterClass.GmHeartBeat value) {
        if (gmHeartBeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGmHeartBeatIsMutable();
          gmHeartBeat_.add(index, value);
          onChanged();
        } else {
          gmHeartBeatBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public Builder addGmHeartBeat(
          GmPacketReaderOuterClass.GmHeartBeat.Builder builderForValue) {
        if (gmHeartBeatBuilder_ == null) {
          ensureGmHeartBeatIsMutable();
          gmHeartBeat_.add(builderForValue.build());
          onChanged();
        } else {
          gmHeartBeatBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public Builder addGmHeartBeat(
          int index, GmPacketReaderOuterClass.GmHeartBeat.Builder builderForValue) {
        if (gmHeartBeatBuilder_ == null) {
          ensureGmHeartBeatIsMutable();
          gmHeartBeat_.add(index, builderForValue.build());
          onChanged();
        } else {
          gmHeartBeatBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public Builder addAllGmHeartBeat(
          java.lang.Iterable<? extends GmPacketReaderOuterClass.GmHeartBeat> values) {
        if (gmHeartBeatBuilder_ == null) {
          ensureGmHeartBeatIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, gmHeartBeat_);
          onChanged();
        } else {
          gmHeartBeatBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public Builder clearGmHeartBeat() {
        if (gmHeartBeatBuilder_ == null) {
          gmHeartBeat_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gmHeartBeatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public Builder removeGmHeartBeat(int index) {
        if (gmHeartBeatBuilder_ == null) {
          ensureGmHeartBeatIsMutable();
          gmHeartBeat_.remove(index);
          onChanged();
        } else {
          gmHeartBeatBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public GmPacketReaderOuterClass.GmHeartBeat.Builder getGmHeartBeatBuilder(
          int index) {
        return getGmHeartBeatFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public GmPacketReaderOuterClass.GmHeartBeatOrBuilder getGmHeartBeatOrBuilder(
          int index) {
        if (gmHeartBeatBuilder_ == null) {
          return gmHeartBeat_.get(index);  } else {
          return gmHeartBeatBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public java.util.List<? extends GmPacketReaderOuterClass.GmHeartBeatOrBuilder> 
           getGmHeartBeatOrBuilderList() {
        if (gmHeartBeatBuilder_ != null) {
          return gmHeartBeatBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gmHeartBeat_);
        }
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public GmPacketReaderOuterClass.GmHeartBeat.Builder addGmHeartBeatBuilder() {
        return getGmHeartBeatFieldBuilder().addBuilder(
            GmPacketReaderOuterClass.GmHeartBeat.getDefaultInstance());
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public GmPacketReaderOuterClass.GmHeartBeat.Builder addGmHeartBeatBuilder(
          int index) {
        return getGmHeartBeatFieldBuilder().addBuilder(
            index, GmPacketReaderOuterClass.GmHeartBeat.getDefaultInstance());
      }
      /**
       * <code>repeated .GmHeartBeat gmHeartBeat = 1;</code>
       */
      public java.util.List<GmPacketReaderOuterClass.GmHeartBeat.Builder> 
           getGmHeartBeatBuilderList() {
        return getGmHeartBeatFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GmPacketReaderOuterClass.GmHeartBeat, GmPacketReaderOuterClass.GmHeartBeat.Builder, GmPacketReaderOuterClass.GmHeartBeatOrBuilder> 
          getGmHeartBeatFieldBuilder() {
        if (gmHeartBeatBuilder_ == null) {
          gmHeartBeatBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GmPacketReaderOuterClass.GmHeartBeat, GmPacketReaderOuterClass.GmHeartBeat.Builder, GmPacketReaderOuterClass.GmHeartBeatOrBuilder>(
                  gmHeartBeat_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          gmHeartBeat_ = null;
        }
        return gmHeartBeatBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GmPacketReader)
    }

    // @@protoc_insertion_point(class_scope:GmPacketReader)
    private static final GmPacketReaderOuterClass.GmPacketReader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GmPacketReaderOuterClass.GmPacketReader();
    }

    public static GmPacketReaderOuterClass.GmPacketReader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GmPacketReader>
        PARSER = new com.google.protobuf.AbstractParser<GmPacketReader>() {
      @java.lang.Override
      public GmPacketReader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GmPacketReader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GmPacketReader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GmPacketReader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GmPacketReaderOuterClass.GmPacketReader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GmHeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GmHeartBeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GmPacketReader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GmPacketReader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024GmPacketReader.proto\"\"\n\013GmHeartBeat\022\023\n" +
      "\013currentTime\030\001 \001(\t\"3\n\016GmPacketReader\022!\n\013" +
      "gmHeartBeat\030\001 \003(\0132\014.GmHeartBeatb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GmHeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GmHeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GmHeartBeat_descriptor,
        new java.lang.String[] { "CurrentTime", });
    internal_static_GmPacketReader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GmPacketReader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GmPacketReader_descriptor,
        new java.lang.String[] { "GmHeartBeat", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
